development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: leave_management
  pool:     5
  username: postgres
  password: postgres
  
production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: leave_management
  pool:     5
  username: postgres
  password: postgres
